" Plugin
source ~/.vimrc.bundle

" Basci
source ~/.vimrc.basic
" Statusline
source ~/.vimrc.statusline
" Indent
source ~/.vimrc.indent
" Apperance
source ~/.vimrc.apperance
" Completion
source ~/.vimrc.completion
" Tags
source ~/.vimrc.tags
" Search
source ~/.vimrc.search
" Move
source ~/.vimrc.moving
" Color
source ~/.vimrc.colors
" Edit
source ~/.vimrc.editing
" Encoding
source ~/.vimrc.encoding
" Other
source ~/.vimrc.misc
" Rely on plugin
source ~/.vimrc.plugins_setting
