#!/bin/sh
ln -s ~/dotfiles/.minttyrc ~/.minttyrc
ln -s ~/dotfiles/.vim ~/.vim
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.vimrc.bundle ~/.vimrc.bundle
ln -s ~/dotfiles/.vimrc.basic ~/.vimrc.basic
ln -s ~/dotfiles/.vimrc.statusline ~/.vimrc.statusline
ln -s ~/dotfiles/.vimrc.indent ~/.vimrc.indent
ln -s ~/dotfiles/.vimrc.apperance ~/.vimrc.apperance
ln -s ~/dotfiles/.vimrc.completion ~/.vimrc.completion
ln -s ~/dotfiles/.vimrc.tags ~/.vimrc.tags
ln -s ~/dotfiles/.vimrc.search ~/.vimrc.search
ln -s ~/dotfiles/.vimrc.moving ~/.vimrc.moving
ln -s ~/dotfiles/.vimrc.colors ~/.vimrc.colors
ln -s ~/dotfiles/.vimrc.editing ~/.vimrc.editing
ln -s ~/dotfiles/.vimrc.encoding ~/.vimrc.encoding
ln -s ~/dotfiles/.vimrc.misc ~/.vimrc.misc
ln -s ~/dotfiles/.vimrc.plugins_setting ~/.vimrc.plugins_setting
ln -s ~/dotfiles/.gvimrc ~/.gvimrc
ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.gitignore_global ~/.gitignore_global
